# Generated by Django 5.1 on 2024-08-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('carga_horaria', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.ManyToManyField(to='gerencia.curso'),
        ),
    ]
