# Generated by Django 5.1 on 2024-08-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0002_curso_aluno_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='curso',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
